"""empty message

Revision ID: d11e851973cd
Revises: d9fa5521a8b1
Create Date: 2022-09-03 14:00:27.683429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11e851973cd'
down_revision = 'd9fa5521a8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('toggleArchive', sa.Boolean(), nullable=True))
    op.alter_column('tasks', 'name', existing_type=sa.String(30), type_=sa.String(500))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'toggleArchive')
    op.alter_column('tasks', 'name', existing_type=sa.String(500), type_=sa.String(30))
    # ### end Alembic commands ###
